{"name": "Test Case 2: Login with valid credentials", "status": "failed", "statusDetails": {"message": "AssertionError: Locator expected to be visible\nActual value: <element(s) not found> \nCall log:\n  - Expect \"to_be_visible\" with timeout 5000ms\n  - waiting for locator(\"div.slider\")", "trace": "browser = <Page url='https://automationexercise.com/'>\n\n    @allure.title(\"Test Case 2: Login with valid credentials\")\n    def test_login_valid(browser):\n        home = HomePage(browser)\n        login = LoginPage(browser)\n    \n        home.go_to()\n>       home.verify_home_visible()\n\ntests\\test_auth.py:12: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <pages.home_page.HomePage object at 0x0000019DDC24D160>\n\n    @allure.step(\"Перевірити, що головна сторінка завантажена\")\n    def verify_home_visible(self):\n>       expect(self.page.locator(\"div.slider\")).to_be_visible()\nE       AssertionError: Locator expected to be visible\nE       Actual value: <element(s) not found> \nE       Call log:\nE         - Expect \"to_be_visible\" with timeout 5000ms\nE         - waiting for locator(\"div.slider\")\n\npages\\home_page.py:14: AssertionError"}, "steps": [{"name": "Перейти на головну сторінку", "status": "passed", "start": 1752404075238, "stop": 1752404080857}, {"name": "Перевірити, що головна сторінка завантажена", "status": "failed", "statusDetails": {"message": "AssertionError: Locator expected to be visible\nActual value: <element(s) not found> \nCall log:\n  - Expect \"to_be_visible\" with timeout 5000ms\n  - waiting for locator(\"div.slider\")\n\n", "trace": "  File \"C:\\Users\\Hp\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\allure_commons\\_allure.py\", line 202, in impl\n    return func(*a, **kw)\n  File \"F:\\QA_Engineer\\TS_Intership\\Playwright_pytest\\pages\\home_page.py\", line 14, in verify_home_visible\n    expect(self.page.locator(\"div.slider\")).to_be_visible()\n    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^\n  File \"C:\\Users\\Hp\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\playwright\\sync_api\\_generated.py\", line 20382, in to_be_visible\n    self._sync(self._impl_obj.to_be_visible(visible=visible, timeout=timeout))\n    ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Hp\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\playwright\\_impl\\_sync_base.py\", line 115, in _sync\n    return task.result()\n           ~~~~~~~~~~~^^\n  File \"C:\\Users\\Hp\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\playwright\\_impl\\_assertions.py\", line 741, in to_be_visible\n    await self._expect_impl(\n    ...<5 lines>...\n    )\n  File \"C:\\Users\\Hp\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\playwright\\_impl\\_assertions.py\", line 75, in _expect_impl\n    raise AssertionError(\n        f\"{out_message}\\nActual value: {actual} {format_call_log(result.get('log'))}\"\n    )\n"}, "start": 1752404080858, "stop": 1752404085884}], "start": 1752404075237, "stop": 1752404085888, "uuid": "15f4ac27-e630-41fc-ac87-77744ab963cd", "historyId": "5024ab45edc8d37f17388bbaa4378baf", "testCaseId": "5024ab45edc8d37f17388bbaa4378baf", "fullName": "tests.test_auth#test_login_valid", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_auth"}, {"name": "host", "value": "DESKTOP-BTCJ9P6"}, {"name": "thread", "value": "7340-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_auth"}]}