{"name": "test_login_with_incorrect_credentials[chromium]", "status": "broken", "statusDetails": {"message": "playwright._impl._errors.Error: Page.goto: net::ERR_CONNECTION_CLOSED at https://automationexercise.com/\nCall log:\n  - navigating to \"https://automationexercise.com/\", waiting until \"load\"", "trace": "page = <Page url='about:blank'>\n\n    def test_login_with_incorrect_credentials(page):\n>       page.goto(\"https://automationexercise.com\")\n\ntests\\test_register_user.py:62: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\nC:\\Users\\Hp\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\playwright\\sync_api\\_generated.py:9002: in goto\n    self._sync(\nC:\\Users\\Hp\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\playwright\\_impl\\_page.py:556: in goto\n    return await self._main_frame.goto(**locals_to_params(locals()))\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nC:\\Users\\Hp\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\playwright\\_impl\\_frame.py:146: in goto\n    await self._channel.send(\nC:\\Users\\Hp\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\playwright\\_impl\\_connection.py:69: in send\n    return await self._connection.wrap_api_call(\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <playwright._impl._connection.Connection object at 0x000001D6177D46E0>\ncb = <function Channel.send.<locals>.<lambda> at 0x000001D6177DB240>\nis_internal = False, title = None\n\n    async def wrap_api_call(\n        self, cb: Callable[[], Any], is_internal: bool = False, title: str = None\n    ) -> Any:\n        if self._api_zone.get():\n            return await cb()\n        task = asyncio.current_task(self._loop)\n        st: List[inspect.FrameInfo] = getattr(\n            task, \"__pw_stack__\", None\n        ) or inspect.stack(0)\n    \n        parsed_st = _extract_stack_trace_information_from_stack(st, is_internal, title)\n        self._api_zone.set(parsed_st)\n        try:\n            return await cb()\n        except Exception as error:\n>           raise rewrite_error(error, f\"{parsed_st['apiName']}: {error}\") from None\nE           playwright._impl._errors.Error: Page.goto: net::ERR_CONNECTION_CLOSED at https://automationexercise.com/\nE           Call log:\nE             - navigating to \"https://automationexercise.com/\", waiting until \"load\"\n\nC:\\Users\\Hp\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\playwright\\_impl\\_connection.py:558: Error"}, "parameters": [{"name": "browser_name", "value": "'chromium'"}], "start": 1752407321281, "stop": 1752407321907, "uuid": "3d268258-86a3-4715-8a6f-521ce72361fa", "historyId": "9bb551dbbd2f8dda594532e91ae15181", "testCaseId": "4c6aabad13cd72c2a29a6c886d995ab9", "fullName": "tests.test_register_user#test_login_with_incorrect_credentials", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_register_user"}, {"name": "host", "value": "DESKTOP-BTCJ9P6"}, {"name": "thread", "value": "17096-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_register_user"}]}